// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iqydfbiqooulawvpvtsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxeWRmYmlxb291bGF3dnB2dHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjQ0OTgsImV4cCI6MjA2ODU0MDQ5OH0.FKLdOTFGJRLN8Q1r5DwTNh6WrG3ToHUpRZKAjQ5FtyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);